Dockerfile
README.md
root/var/www/wallabag/app/config/parameters.yml

Hi!
Because the standard approach of using localhost as a mail server doesn't work in docker images, I added a few environment variables to make the email settings configurable with e.g. docker-compose.

Make email settings configurable

---

root/etc/nginx/nginx.conf

With the default client_max_body_size (1M), import cannot be used.
Raise the limit to 50M.
Maybe this parameter should be configurable via an environment variable?

Increase max body size from nginx

---

Dockerfile
README.md
root/etc/ansible/entrypoint.yml
root/etc/ansible/templates/parameters.yml.j2

DB migration is documented in the docs. Running it everytime didnt worked for me if its a fresh db.

2.1.1 image

---

root/etc/s6/.s6-svscan/finish

Enables a clean shutdown of the docker container, i.e. removes the following error messages while shutting down:
```
s6-svscan: warning: unable to exec finish script .s6-svscan/finish: No such file or directory
s6-svscan: warning: executing into .s6-svscan/crash
s6-svscan: fatal: unable to exec .s6-svscan/crash: No such file or directory
```

Add .s6-svscan/finish.

---

Dockerfile

If php7-zlib is missing the pocket importer worker dies on a exception because gzuncompress is undefined.

Install php7-zlib

---

README.md
root/etc/ansible/entrypoint.yml

This PR adds an env variable POPULATE_DATABASE, default to True.
If set to False, the ansible playbook won't try to connect to the mysql or postgresql DB as admin to create a user and populate the DB.
It is usefull in case of migration of an existing setup to docker (but keeps the existing DB).

Add a POPULAtE_DATABASE env to use an existing wallabag DB

---

Dockerfile
README.md
root/entrypoint.sh
root/etc/ansible/entrypoint.yml
root/etc/ansible/templates/parameters.yml.j2
root/var/www/wallabag/app/config/parameters.yml

made the changes to get 2.2.1 running plus added a migrate command to
the entrypoint. documented it in the readme.

Version bumb to 2.2.1 and added migrate command

---

Dockerfile
README.md
root/etc/ansible/entrypoint.yml

* MariaDB encoding is set when creating DB through the entrypoint
* Cleaning Dockerfile
* Removed `POSTGRES_USER`
* Combined run commands
* Changed deprecated `MAINTAINER` to `LABEL`

MariaDB default encoding utf8mb4 and maintenance

---

Dockerfile

there are alot of php fixes in edge. alot of people have problems with
php and older kernel versions to collect random data.
also included a alpine upgrade command. this will prevent docker from
building a wallabag image with older system files.

switched to alpine edge

---

README.md

closes #101 Typo on readme which leads to a docker syntax error.

101 - Typo on readme

---

README.md
root/etc/ansible/entrypoint.yml
root/etc/ansible/templates/parameters.yml.j2
tests/docker-compose.postgresql.yml

* Add SYMFONY__ENV__DATABASE_DRIVER_CLASS environment variable which can
be set to the necessary driver class for Postgres 10
* Use this in travis.yml
* Encrypt the password - Postgres 10 no longer allows unencrypted passwords

Support Postgres 10

---

Dockerfile

While investigating of wallabag/wallabag#3723:
- I could not build wallabag docker image with edge
- I succeeded in building with latest
- building with latest resolved wallabag/wallabag#3723
Additionally, alpine recommends against using edge for end users ([0][]).
[0]: https://wiki.alpinelinux.org/wiki/Edge

Use alpine:latest instead of alpine:edge for base

---

README.md

I opened an [issue](https://github.com/wallabag/wallabag/issues/3700) on wallabag/wallabag, where emoji were causing insert errors. I found the `SYMFONY__ENV__DATABASE_CHARSET` environment variable referenced in another issue. Setting that variable to `utf8mb4` resolved my issues.

Added SYMFONY__ENV__DATABASE_CHARSET envorinment variable to README.

---

README.md
root/etc/ansible/entrypoint.yml
root/etc/ansible/templates/parameters.yml.j2

Allow setting of the Redis options as run time options.
The documentation is updated.

Add redis environmental variables

---

README.md

The `SYMFONY__ENV__LOCALE` variable is used in [ansible playbook](root/etc/ansible/entrypoint.yml) but not documented in README.

Add locale environment variable to README

---

Dockerfile

This PR adds 2 instructions to the Docker image build, making sure that `iconv` is setup properly.
This fixes https://github.com/wallabag/wallabag/issues/4011
For more context about the actual underlying issue that this fixes, you can read up
* https://github.com/docker-library/php/issues/240
* https://github.com/docker-library/php/issues/428
Kind regards

Fix iconv setup to make it support non-ASCII encodings

---

root/etc/nginx/nginx.conf

Problem: Nginx is only binding to the IPv4. Deployments with IPv6 require forking the image or overwriting `nginx.conf`.
Solution: Edit `nginx.conf` to listen to both IPv4 and IPv6 by making it listen on `[::]:80`.
Note: This may be related and contradictory to #54

Fix Nginx was not binding on IPv6

---

Dockerfile

Problem: I try to build image for wallabag 2.4-dev as of Feb 29, 2020.
The building fails due to two missing packages:
* py-mysqldb
* py-psycopg2
It seems these two packages are included in alpine:3.10, not yet in
alpine:latest. After launching wallabag 2.4-dev, a zhihu page reports
error and wallabag suggests to install php7-intl.
Solution:
* Fix alpine version to 3.10. The reason is also to avoid
CVE-2019-5021 (alpine set root password to NULL). 3.10 is not affected.
In case some users use tag 3.9 and happen to have 3.9.2, then they may
be affected.
* Add php7-intl to meet new requirement

Prepare for wallabag 2.4

---

Dockerfile

This PR updates the Alpine base image to the latest version (3.12).
As the package names for the Python MySQL and PgSQL libraries changed between Alpine version these were adapted as well.

Update Alpine base image to 3.12

---

Dockerfile

Running `make update` requires make and bash to be installed.
Closes #237

Fix upgrading to 2.4 requires make and bash

---

README.md

The default value of this variable leads to a lot of issues with assets
when new comers try wallabag. This change should reduce the occurrence of
this kind of issue.

Update README to include SYMFONY__ENV__DOMAIN_NAME in the quickstart

---

README.md

This PR adds in a health check that can used for reporting, monitoring, or autohealing, as well as a `depends_on` statement that ensures wallabag comes up only once the DB and Redis are up.

Add healthcheck and dependencies to docker-compose example

---

Dockerfile

Install the latest known 2.2 version instead.
See https://github.com/wallabag/wallabag/pull/5708

wallabag isn't compatible with Composer 2.3

---

.github/workflows/publish.yml

This commit allows Github actions to automatically create and publish Docker images for armv7 and arm64 architecture (e. g. Raspberry Pi).
I really would like to use Wallabag on my Raspberry Pi. Unfortunately there is no official Docker image, only community provided solutions. So I decided to open up this pull request to publish also Docker images for ARM architecture. This should also allow the closure of #277 . 
For further information regarding the changes inside the publish file I also added links to the documentation.

Automatically build ARM docker images on release

---

Dockerfile

* Git package not required
* Reduced Docker image size in 129 MB (808 MB -> 679 MB)
* Docker build time reduced in +1 min (no git pull)
Related #269 #270

Install from TAR file and reduce image size

---

README.md
root/etc/ansible/entrypoint.yml
root/etc/ansible/templates/parameters.yml.j2

For people in need to migrate to the docker version from a previous installed wallabag instance defined with a database prefix.
Should fix https://github.com/wallabag/docker/issues/304

Add ability to define `database_table_prefix`

---

root/etc/nginx/fastcgi_params
root/etc/nginx/nginx.conf

Related #77, #264.
This PR changes the `nginx.conf `of wallabag-docker to enable fastcgi HTTPS especially in case of reverse-proxy settings.
The idea is came from @blopware ['s workaround](https://github.com/wallabag/docker/issues/77#issuecomment-609423822) and https://serverfault.com/a/527809.

Fix nginx.conf for reverse-proxy with HTTPS

---

Dockerfile

The fix was required for Alpine 3.10 but it's already fixed in Alpine 3.16
Original fix and issue => https://github.com/wallabag/docker/commit/503114fcbaedfd4f51311cd2e5e28ca2ac8c94b4
Package with the issue 3.10 => https://pkgs.alpinelinux.org/packages?name=gnu-libiconv&branch=v3.10&repo=&arch=&maintainer=
Fixed package 3.16 => https://pkgs.alpinelinux.org/packages?name=gnu-libiconv&branch=v3.16&repo=&arch=&maintainer=

Remove fix for gnu-libiconv (already fixed in Alpine 3.16)

---

.github/workflows/test.yml
conftest.py
tests/test_login.py

This PR moves logic in charge of starting docker service `wallabag` in pytest, using pytest-docker. This let us avoid putting sleep steps in the CI.
As pytest-docker does not provide a way to print service logs, we still rely on additional calls to `docker-compose logs` and `docker-compose down -v` after tests are finished, see https://github.com/avast/pytest-docker/issues/13

tests: move docker service start in pytest

---

root/etc/wallabag/parameters.template.yml

Note: tests are failing because we build the docker image with wallabag 2.6.1

Remove 2fa parameter

---

Dockerfile

Add Wallabag bin path to environment path so it's commands (i.e `console cache:clear --env=prod`) can be run from anywhere.

Add wallabag/bin to PATH

---

Dockerfile

Sets the workdir to navigate to the wallabag folder when entering.
Makes it much easier to not have to always drill all the way down each time you first shell in.

Change default workdir

---

Dockerfile

There's no apparent interest in using alpine's edge repository introduced by #376

Use php81-pecl-imagick from default repository

---

Dockerfile

~~A proposal to build assets as part of the building of the docker image.~~
Use the release archive as assets are now removed from the repository, see https://github.com/wallabag/wallabag/pull/6982
This will help to avoid having built assets versionned in the git source code and avoid hack like [this one](https://github.com/wallabag/wallabag/pull/6823#issuecomment-1675575464) in the proposal to use Webpack Encore

Use the release archive instead of the git archive

---

root/etc/nginx/nginx.conf

Tested changing this live on a IPv6-only kubernetes cluster. Appears to be working. Adding to docker image.

Update nginx.conf to work with IPv6

---

README.md

Most example docker-compose files include restart: unless-stopped or restart: always. This being absent on Wallabag's example leads to unexpected downtime upon server restart

Add restart: unless-stopped to example docker-compose

---

README.md

This PR changes the health check target endpoint used in the docker-compose example as `http://localhost` leads to a 302 redirect to `/login` and a fetch of 5 KB every minute.
`/api/info` is lighter for this purpose.

doc: change docker-compose healthcheck target

---

README.md
root/entrypoint.sh
root/etc/wallabag/php-wallabag.template.ini

This PR is based on #374 but it uses envsubst instead of sed-ing php.ini file
Supersedes #374
Fixes #124

Add support of PHP memory limit in variables

---

Dockerfile

On my install, I was seeing ~700ms responses to load an article. Turning this on brings them down to 80-100ms.
The opcache extension should really be enabled by default in all installations. Even on locals for development purposes there's no downside.
I thought about additionally enabling `opcache.validate_timestamps`, which does affect manually exec'ing into the container and hacking files, but given there's no opcache at all this seems like a good first step.

Install the opcache extension #162

---

Dockerfile
README.md

- Move the healthcheck from the docker-compose example to the actual image. That makes sure all user of the image automatically get the healthcheck.
- Change to `curl --fail || exit 1` as suggested in [docker documentation](https://docs.docker.com/reference/dockerfile/#healthcheck)
- Add `--silent --show-error` so that docker health state contains the output of the HTTP call instead of curl progress bar
- Set the user agent to make the logs more readable

Add healthcheck to image

---

root/etc/wallabag/parameters.template.yml

modified parameters template so it supports rabbitmq configuration from environment variables
Closes #163

rabbitmq support in docker
