root/etc/nginx/nginx.conf

Errors to error.log and access to access.log

Fix logs naming

---

Dockerfile

But I can't push the updated image on docker hub ;-)

Update Dockerfile for 2.0.6 release

---

README.md
tests/test_login.py

thank you @Strubbl!
again im sorry for my pushing. its still ok to discuss about the best way of testing the image.

Login testing works now

---

Dockerfile

To merge when wallabag 2.0.8 will be released (in few hours).

wallabag 2.0.8

---

Dockerfile
root/etc/ansible/entrypoint.yml
root/etc/ansible/templates/parameters.yml.j2
root/var/www/wallabag/app/config/parameters.yml

i had to add new keys to parameters.yml to get it working. used this to do some cleanups because of the non functioning env variables in parameters.yml. using a ansible template instead.

version 2.1.2 and some cleanups

---

root/etc/ansible/entrypoint.yml
root/etc/ansible/templates/parameters.yml.j2

set email settings through ansible template

---

Dockerfile

Don't merge it now, we need to wait to release wallabag 2.1.4.

Dockerfile for 2.1.4

---

Dockerfile

2.1.6 will be released in coming hours.

Update Dockerfile for wallabag 2.1.6

---

README.md
root/entrypoint.sh
root/etc/ansible/entrypoint.yml

This adds an option to run the redis based import workers.

Add option to run redis based import workers

---

Dockerfile
root/entrypoint.sh

alot of things got added to alpine 3.5 and we dont need to use the bleeding edge dev version of alpine to get wallabag running.

using alpine 3.5 instead of edge

---

Dockerfile

Looks like is is stuck with an old version :)

Update to 2.3.3

---

Dockerfile

Related to https://github.com/wallabag/wallabag/issues/3806

Add php7-tidy

---

Dockerfile

This allows for setting the timezone using the TZ environment variable.

Adds tzdata to installed packages

---

README.md
root/etc/ansible/entrypoint.yml
root/etc/ansible/templates/parameters.yml.j2
root/var/www/wallabag/app/config/parameters.yml

Add config for sentry into parameters.yml

Config: add sentry_dsn entry

---

root/etc/ansible/templates/parameters.yml.j2

Sentry: fix template parameters

---

README.md
root/etc/ansible/entrypoint.yml
root/etc/ansible/templates/parameters.yml.j2

Following https://github.com/wallabag/docker/pull/193
Fix #192

Add env variables for two-factor auth

---

root/etc/php7/php.ini

Set "expose_php" to "Off" in php.ini

---

root/entrypoint.sh

Fix `-e=prod` parameter

---

README.md
root/etc/ansible/entrypoint.yml
root/etc/ansible/templates/parameters.yml.j2

The new parameter is expected to land in wallabag 2.4.1, see https://github.com/wallabag/wallabag/pull/4301

Add new parameter server_name for 2FA issuer

---

.github/workflows/publish.yml
.github/workflows/test.yml

It removed all warning during the build.

Update actions to latest version

---

Dockerfile

Update Alpine 3.16

---

.github/workflows/test.yml

This PR updates Python and fixes some warnings in the GitHub Actions.

Update Python version in GitHub Actions

---

root/etc/wallabag/parameters.template.yml

To prepare for Symfony 5, see https://github.com/wallabag/wallabag/pull/6809

Rename root_dir to project_dir

---

README.md
root/etc/wallabag/parameters.template.yml
tests/test_login.py

See https://github.com/wallabag/wallabag/pull/6791

Change public registration to false by default

---

Dockerfile

Revert "Update Dockerfile to release 2.6.5"

---

Dockerfile

See https://github.com/wallabag/wallabag/releases/tag/2.6.6

Prepare 2.6.6

---

Dockerfile

Add imagick extension to support gif.

Support for gif.

---

Dockerfile

See https://github.com/wallabag/wallabag/releases/tag/2.6.7

Prepare 2.6.7

---

Dockerfile

See https://github.com/wallabag/wallabag/releases/tag/2.6.8

Prepare 2.6.8

---

root/entrypoint.sh

If we use a local folder volume binding, install_wallabag was failing because of missing file and permission issues.
This reworks the way we initially create the database when it is missing or empty.
Superseeds #386
Fixes #316 #346

Fix SQLite provisioning

---

Dockerfile

See https://github.com/wallabag/wallabag/releases/tag/2.6.9

Prepare 2.6.9

---

root/etc/nginx/nginx.conf

Support dualstack listen on nginx

---

README.md

As suggested in #381. Fixes #342 and #381

Update example compose file mariadb healthcheck command
